name: Bump version on main

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  bump-version:
    name: Bump package.json version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Bump patch version
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # incrementa versão patch e cria commit
          npm version patch -m "chore: bump version to %s [skip ci]"

      - name: Push commit
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
